### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by osamahamad** [Healdb/Elevate#3]
Hi,

On python2 - requirements.txt installed 

python elevate.py -o "reddit_domains.txt" -n "uber"

```
/usr/local/lib/python2.7/dist-packages/OpenSSL/crypto.py:14: CryptographyDeprecationWarning: Python 2 is no longer supported by the Python core team. Support for it is now deprecated in cryptography, and will be removed in the next release.
  from cryptography import utils, x509
Traceback (most recent call last):
  File "elevate.py", line 4, in <module>
    from utils import Utilities
  File "/oneline/Elevate/utils.py", line 6, in <module>
    class Utilities:
  File "/oneline/Elevate/utils.py", line 10, in Utilities
    keys = Sources()
  File "/oneline/Elevate/sources.py", line 9, in __init__
    apiKeys[line[0]] = line[1].strip()
IndexError: list index out of range

```

on python3 - requirements also satisfied 

```
python3 elevate.py -o "uber-domains.out" -d "uber.com"
Traceback (most recent call last):
  File "elevate.py", line 4, in <module>
    from utils import Utilities
  File "/oneline/Elevate/utils.py", line 6, in <module>
    class Utilities:
  File "/oneline/Elevate/utils.py", line 10, in Utilities
    keys = Sources()
  File "/oneline/Elevate/sources.py", line 9, in __init__
    apiKeys[line[0]] = line[1].strip()
IndexError: list index out of range

```

Tested on python3.8 3.7 and python2 does not really remember 2 exact version.

**Comment by marz-hunter** [comment]
error in python 2   

Traceback (most recent call last):
  File "elevate.py", line 86, in <module>
    elevate(sys.argv[1:])
  File "elevate.py", line 79, in elevate
    totalDomains = totalDomains.union(asnSearch(utils,partialOrgName,verbose))
  File "elevate.py", line 27, in asnSearch
    orgIndexes = input("Select CSV indexes for Organizations you want to investigate. Ex: 1,7,13\n").split(",")
AttributeError: 'int' object has no attribute 'split'

**Comment by Healdb** [comment]
This tool should be run with python3. This error is likely because of a malformed config.txt file, it should be in the following format - 

```
whoxy:WHOXY_API_KEY
whoisxml:WHOISXML_API_KEY
```

**Comment by osamahamad** [comment]
But I think I'm pretty sure about my config @Healdb 

```
whoxy:a26c25ba65860XXXXX5dXXXX7bbdcf
whoisxml:at_9onrXXXXXXX9aG2NOPdwRooXMelm0
```

**Comment by Healdb** [comment]
Make sure there aren't any extra lines in the file or characters
